sudo: false
language: node_js
os:
  - linux
  - osx
  - windows
node_js:
  - 7
  - 8
  - 9
  - 10
  - 11
before_script:
    - cd packages/doodoo.js
    - npm install
script:
    - npm run cover
after_script:
    - npm install codecov
    - ./node_modules/.bin/codecov