sudo: false
language: node_js
os:
  - linux
  - osx
  - windows
node_js:
  - 8
  - 9
  - 10
  - 11
before_script:
    - cd packages/doodoo.js
    - yarn install
script:
    - yarn run cover
after_script:
    - yarn install codecov
    - ./node_modules/.bin/codecov